tudo: compilaar rodar

compilar:
	gcc -o rAAOrganizacaoDeProjeto ODPSoma.c ODPSubtrair.c ODPDividir.c ODPMultiplicar.c rAAOrganizacaoDeProjeto.c -Wall
	gcc -c ODPSoma.c
	gcc -c ODPSubtrair.c
	gcc -c ODPMultiplicar.c
	gcc -c ODPDividir.c
	./Compilado
compilaar:
	gcc -o rAAOrganizacaoDeProjeto ODPSoma.c ODPSubtrair.c ODPDividir.c ODPMultiplicar.c rAAOrganizacaoDeProjeto.c -Wall
	gcc -c ODPSoma.c
	gcc -c ODPSubtrair.c
	gcc -c ODPMultiplicar.c
	gcc -c ODPDividir.c
rodar:
	./rAAOrganizacaoDeProjeto